/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.psbo.eta.ui;


import com.psbo.eta.controller.ColumnPemohon;
import com.psbo.eta.controller.TableModelPemohon;
import com.psbo.eta.model.CRUD;
import com.psbo.eta.model.MyConnection;
import com.psbo.eta.model.Pemohon;
import com.psbo.eta.model.Preview;
import com.psbo.eta.model.Setting;
import com.psbo.eta.model.SettingToDatabaseTemplate;
import com.psbo.eta.model.Transaksi;
import java.awt.Font;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Multiverse
 * Develop by E.T.A
 */
public class Home extends javax.swing.JFrame {
    private final TableModelPemohon tableModelPemohon;
    /**
     * Creates new form Home
     */
    public Home() throws SQLException {
        tableModelPemohon = new TableModelPemohon();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_HORIZ);
        panelContain.setBorder(BorderFactory.createTitledBorder("Isi Formulir"));
        panelIdentitas.setBorder(BorderFactory.createTitledBorder("Address"));
        initComponentsCustomePemohon();
        loadTabelPemohon();
        initIdPemohon();
        initButtonToFalse();
        identitasRt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panelContain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        namaTxt = new javax.swing.JTextField();
        tanggalTxt = new javax.swing.JTextField();
        pekerjaanTxt = new javax.swing.JTextField();
        AlamatTxt = new javax.swing.JTextField();
        kewarganegaraanCbx = new javax.swing.JComboBox<>();
        agamaCbx = new javax.swing.JComboBox<>();
        jenisKelaminCbx = new javax.swing.JComboBox<>();
        simpanBtn = new javax.swing.JButton();
        batalBtn = new javax.swing.JButton();
        perbaharuiBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        labelPrint = new javax.swing.JLabel();
        labelPreview = new javax.swing.JLabel();
        persyaratanLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        scrollPemohon = new javax.swing.JScrollPane();
        tablePemohon = new javax.swing.JTable();
        refreshLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cariTxt = new javax.swing.JTextField();
        cariBtn = new javax.swing.JButton();
        resetLabel = new javax.swing.JLabel();
        panelIdentitas = new javax.swing.JPanel();
        labelNamaRt = new javax.swing.JLabel();
        labelNamaRw = new javax.swing.JLabel();
        labelNamaDesa = new javax.swing.JLabel();
        labelNamaKecamatan = new javax.swing.JLabel();
        labelNamaKabupaten = new javax.swing.JLabel();
        labelNamaProvinsi = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        perbaharuiInformasiBtn = new javax.swing.JButton();
        refreshIdentitasRt = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        labelNoRt = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        labelNoRw = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        signout = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        settingMenu = new javax.swing.JMenu();
        settingTemplate = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        petunjukMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        aboutUsMenu = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Surat Pengantar Pembuatan Kartu Keluarga - Home");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Input Data Pemohon");
        panelContain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel2.setText("ID");
        panelContain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 30, -1));

        jLabel3.setText("Nama Pemohon");
        panelContain.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jLabel4.setText("Tanggal Lahir");
        panelContain.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel5.setText("Jenis Kelamin");
        panelContain.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jLabel6.setText("Agama");
        panelContain.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        jLabel8.setText("Pekerjaan");
        panelContain.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel9.setText("Kewarganegaraan");
        panelContain.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel10.setText("Alamat");
        panelContain.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        jLabel11.setText(":");
        panelContain.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel12.setText(":");
        panelContain.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel13.setText(":");
        panelContain.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        jLabel14.setText(":");
        panelContain.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jLabel16.setText(":");
        panelContain.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        jLabel17.setText(":");
        panelContain.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLabel18.setText(":");
        panelContain.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jLabel19.setText(":");
        panelContain.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        idText.setEditable(false);
        panelContain.add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 170, -1));
        panelContain.add(namaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 150, -1));
        panelContain.add(tanggalTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 170, -1));
        panelContain.add(pekerjaanTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 170, -1));
        panelContain.add(AlamatTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 230, -1));

        kewarganegaraanCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WNI", "WNA" }));
        panelContain.add(kewarganegaraanCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 90, -1));

        agamaCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "kristen", "hindu", "budha", "konghuchu" }));
        panelContain.add(agamaCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 100, -1));

        jenisKelaminCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Perempuan" }));
        panelContain.add(jenisKelaminCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });
        panelContain.add(simpanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 110, 30));

        batalBtn.setText("Batal");
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });
        panelContain.add(batalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 110, 30));

        perbaharuiBtn.setText("Perbaharui");
        perbaharuiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perbaharuiBtnActionPerformed(evt);
            }
        });
        panelContain.add(perbaharuiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 110, 30));

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });
        panelContain.add(hapusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 110, 30));

        labelPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/psbo/eta/assets/print.png"))); // NOI18N
        labelPrint.setText("Print");
        labelPrint.setToolTipText("Ketuk 2x Untuk Mencetak Formulir");
        labelPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPrintMouseClicked(evt);
            }
        });
        panelContain.add(labelPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        labelPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/psbo/eta/assets/text-document.png"))); // NOI18N
        labelPreview.setText("Preview");
        labelPreview.setToolTipText("Ketuk 2x Untuk Melihat Preview dari Formulir");
        labelPreview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPreviewMouseClicked(evt);
            }
        });
        panelContain.add(labelPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));

        persyaratanLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/psbo/eta/assets/list.png"))); // NOI18N
        persyaratanLabel.setText("Persyaratan");
        persyaratanLabel.setToolTipText("Ketuk 2x Untuk Melihat Kelengkapan Persyaratan");
        persyaratanLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persyaratanLabelMouseClicked(evt);
            }
        });
        panelContain.add(persyaratanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));
        panelContain.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 260, 10));

        jPanel1.add(panelContain, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 840, 380));

        tablePemohon.setAutoCreateColumnsFromModel(false);
        tablePemohon.setModel(tableModelPemohon);
        tablePemohon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePemohonMouseClicked(evt);
            }
        });
        scrollPemohon.setViewportView(tablePemohon);

        jPanel1.add(scrollPemohon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1330, 220));

        refreshLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/psbo/eta/assets/reload.png"))); // NOI18N
        refreshLabel.setText("Refresh Table");
        refreshLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshLabelMouseClicked(evt);
            }
        });
        jPanel1.add(refreshLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Cari Identitas Pemohon");

        cariBtn.setText("cari");
        cariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cariBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cariBtn))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 840, 30));

        resetLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/psbo/eta/assets/garbage.png"))); // NOI18N
        resetLabel.setToolTipText("Reset Tabel");
        resetLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetLabelMouseClicked(evt);
            }
        });
        jPanel1.add(resetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 400, -1, -1));

        panelIdentitas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelIdentitas.add(labelNamaRt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 140, 20));
        panelIdentitas.add(labelNamaRw, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 170, 20));
        panelIdentitas.add(labelNamaDesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, 20));
        panelIdentitas.add(labelNamaKecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 120, 20));
        panelIdentitas.add(labelNamaKabupaten, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 130, 20));
        panelIdentitas.add(labelNamaProvinsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 140, 20));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel21.setText("Identitas RT");
        panelIdentitas.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel22.setText("- Nama :");
        panelIdentitas.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel23.setText("- Nama Rw :");
        panelIdentitas.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel24.setText("- Nama Desa :");
        panelIdentitas.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel25.setText("- Nama Kecamatan :");
        panelIdentitas.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel26.setText("- Nama Kabupaten :");
        panelIdentitas.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel27.setText("- Nama Provinsi :");
        panelIdentitas.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        perbaharuiInformasiBtn.setText("Perbaharui Informasi");
        perbaharuiInformasiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perbaharuiInformasiBtnActionPerformed(evt);
            }
        });
        panelIdentitas.add(perbaharuiInformasiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 170, 30));

        refreshIdentitasRt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/psbo/eta/assets/reload.png"))); // NOI18N
        refreshIdentitasRt.setToolTipText("Refresh Identitas RT");
        refreshIdentitasRt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshIdentitasRtMouseClicked(evt);
            }
        });
        panelIdentitas.add(refreshIdentitasRt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel28.setText("- RT/RW :");
        panelIdentitas.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        panelIdentitas.add(labelNoRt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 20, 20));

        jLabel30.setText("/");
        panelIdentitas.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));
        panelIdentitas.add(labelNoRw, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 20, 20));

        jPanel1.add(panelIdentitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 380));
        jPanel1.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 110, 70, 30));

        jScrollPane1.setViewportView(jPanel1);

        fileMenu.setText("File");

        signout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/psbo/eta/assets/log-out.png"))); // NOI18N
        signout.setText("Sign-out");
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });
        fileMenu.add(signout);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/psbo/eta/assets/exit.png"))); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        fileMenu.add(exit);

        jMenuBar2.add(fileMenu);

        settingMenu.setText("Setting");

        settingTemplate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        settingTemplate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/psbo/eta/assets/settings.png"))); // NOI18N
        settingTemplate.setText("Template");
        settingTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingTemplateActionPerformed(evt);
            }
        });
        settingMenu.add(settingTemplate);

        jMenuBar2.add(settingMenu);

        helpMenu.setText("Help");

        petunjukMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/psbo/eta/assets/user-guide.png"))); // NOI18N
        petunjukMenu.setText("Petunjuk Penggunaan");
        helpMenu.add(petunjukMenu);
        helpMenu.add(jSeparator1);

        aboutUsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/psbo/eta/assets/about-us.png"))); // NOI18N
        aboutUsMenu.setText("About Us");
        aboutUsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsMenuActionPerformed(evt);
            }
        });
        helpMenu.add(aboutUsMenu);

        jMenuBar2.add(helpMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1356, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void identitasRt() throws SQLException{
        
        SettingToDatabaseTemplate stdt = new SettingToDatabaseTemplate();
        Vector<Setting> vSetting = stdt.executeSelectSettingTemplate();

        for (Setting setting : vSetting) {
            labelNoRt.setText           (setting.getNo_rt());
            labelNoRw.setText           (setting.getNo_rw());
            labelNamaRt.setText         (setting.getNama_rt());
            labelNamaRw.setText         (setting.getNama_rw());
            labelNamaDesa.setText       (setting.getDesa());
            labelNamaKecamatan.setText  (setting.getKecamatan());
            labelNamaKabupaten.setText  (setting.getKabupaten());
            labelNamaProvinsi.setText   (setting.getProvinsi());
        }
        
    }
    
    //visible aboutUs
    private void aboutUsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsMenuActionPerformed
        AboutUs au = new AboutUs(this, true);
        au.setVisible(true);
    }//GEN-LAST:event_aboutUsMenuActionPerformed
    //visible setting template
    private void settingTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingTemplateActionPerformed
        SettingUI st;
        try {
            st = new SettingUI(this, true);
            st.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_settingTemplateActionPerformed
    //saat frame pertama kali muncul buat fungsi update dan delete tidak berfungsi
    private void initButtonToFalse(){
        simpanBtn.setEnabled(true);
        perbaharuiBtn.setEnabled(false);
        hapusBtn.setEnabled(false);
    }
    //mengembalikan nilai enable fungsi simpan
    private void initButtonToTrue(){
        simpanBtn.setEnabled(false);
        perbaharuiBtn.setEnabled(true);
        hapusBtn.setEnabled(true);
    }
    //sign-out aplikasi to login
    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signoutActionPerformed
    //refresh tablePemohon
    private void refreshLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLabelMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            CRUD crud = new CRUD();
            try {
                Vector<Pemohon> vPmn = crud.executeSelect();
                int i = 0;
                tableModelPemohon.setListPemohon(vPmn);
                tableModelPemohon.fireTableDataChanged();
                for (Pemohon pmn : vPmn) {
                    tableModelPemohon.setValueAt(pmn.getNo(), i, 1);
                    tableModelPemohon.setValueAt(pmn.getId(), i, 2);
                    tableModelPemohon.setValueAt(pmn.getNama_pemohon(), i, 3);
                    tableModelPemohon.setValueAt(pmn.getPekerjaan(), i, 4);
                    tableModelPemohon.setValueAt(pmn.getKewarganegaraan(), i, 5);
                    tableModelPemohon.setValueAt(pmn.getDob(), i, 6);
                    tableModelPemohon.setValueAt(pmn.getAlamat(), i, 7);
                    tableModelPemohon.setValueAt(pmn.getGender(), i, 8);
                    tableModelPemohon.setValueAt(pmn.getAgama(), i, 9);
                    i++;
                }
                System.out.println("Berhasil kawan namun belum ada yang berubah");
                initIdPemohon();
            } catch (SQLException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_refreshLabelMouseClicked
    //simpan data pemohon
    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        Pemohon pmn = new Pemohon();
        CRUD crud = new CRUD();
        if (namaTxt.getText().isEmpty() || pekerjaanTxt.getText().isEmpty() ||
            tanggalTxt.getText().isEmpty() || AlamatTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inputan tidak boleh kosong");
        }else{
            try {
                Vector<Pemohon> vPmn;
                int i = 0;
                int no = 0;
                try {
                    vPmn = crud.executeSelect();
                    for (Pemohon pemohon : vPmn) {
                        no  = pemohon.getNo();
                        i++;
                    }
                    no = no+1;
                } catch (SQLException ex) {
                    Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                pmn.setNo               (no);
                pmn.setId               (idText.getText());
                pmn.setNama_pemohon     (namaTxt.getText());
                pmn.setPekerjaan        (pekerjaanTxt.getText());
                pmn.setKewarganegaraan  ((String)kewarganegaraanCbx.getSelectedItem());
                pmn.setDob              (tanggalTxt.getText());
                pmn.setAlamat           (AlamatTxt.getText());
                pmn.setGender           ((String)jenisKelaminCbx.getSelectedItem());
                pmn.setAgama            ((String)agamaCbx.getSelectedItem()); 
                
                crud.executeInsertPemohon(pmn);
                JOptionPane.showMessageDialog(this, "Data Pemohon Berhasil disimpan");
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                Vector<Pemohon> vPmn = crud.executeSelect();
                int i = 0;
                tableModelPemohon.setListPemohon(vPmn);
                tableModelPemohon.fireTableDataChanged();
                for (Pemohon pemohon : vPmn) {
                    tableModelPemohon.setValueAt(pemohon.getNo(), i, 1);
                    tableModelPemohon.setValueAt(pemohon.getId(), i, 2);
                    tableModelPemohon.setValueAt(pemohon.getNama_pemohon(), i, 3);
                    tableModelPemohon.setValueAt(pemohon.getPekerjaan(), i, 4);
                    tableModelPemohon.setValueAt(pemohon.getKewarganegaraan(), i, 5);
                    tableModelPemohon.setValueAt(pemohon.getDob(), i, 6);
                    tableModelPemohon.setValueAt(pemohon.getAlamat(), i, 7);
                    tableModelPemohon.setValueAt(pemohon.getGender(), i, 8);
                    tableModelPemohon.setValueAt(pemohon.getAgama(), i, 9);
                    i++;
                }
                
                initIdPemohon();
                resetKonten();
            } catch (SQLException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_simpanBtnActionPerformed
    //kosongkan nilai konten
    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        resetKonten();
        initButtonToFalse();
    }//GEN-LAST:event_batalBtnActionPerformed
    //kondisi ketika tablepemohon di click
    Persyaratan prstn;
    private void tablePemohonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePemohonMouseClicked
        if (evt.getClickCount() == 2) {
            //pilih baris dari tabel
            int row = tablePemohon.getSelectedRow();
            //tampung semua nilai kedalam variabel
            String no               = tablePemohon.getValueAt(row, 0).toString();
            String id               = tablePemohon.getValueAt(row, 1).toString();
            String nama_pemohon     = tablePemohon.getValueAt(row, 2).toString();
            String pekerjaan        = tablePemohon.getValueAt(row, 3).toString();
            String kewarganegaraan  = tablePemohon.getValueAt(row, 4).toString();
            String dob              = tablePemohon.getValueAt(row, 5).toString();
            String alamat           = tablePemohon.getValueAt(row, 6).toString();
            String gender           = tablePemohon.getValueAt(row, 7).toString();
            String agama            = tablePemohon.getValueAt(row, 8).toString();
            
            idText.setText(id);
            namaTxt.setText(nama_pemohon);
            pekerjaanTxt.setText(pekerjaan);
            kewarganegaraanCbx.setSelectedItem(kewarganegaraan);
            tanggalTxt.setText(dob);
            AlamatTxt.setText(alamat);
            jenisKelaminCbx.setSelectedItem(gender);
            agamaCbx.setSelectedItem(agama);
            initButtonToTrue();
            
        }
    }//GEN-LAST:event_tablePemohonMouseClicked
    //perbaharui identitas pembuat surat pengantar
    private void perbaharuiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perbaharuiBtnActionPerformed
        Pemohon pmn = new Pemohon();
        CRUD crud = new CRUD();
        if (namaTxt.getText().isEmpty() || pekerjaanTxt.getText().isEmpty() ||
            tanggalTxt.getText().isEmpty() || AlamatTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inputan tidak boleh kosong");
        }else{
            try {
                pmn.setId               (idText.getText());
                pmn.setNama_pemohon     (namaTxt.getText());
                pmn.setPekerjaan        (pekerjaanTxt.getText());
                pmn.setKewarganegaraan  ((String)kewarganegaraanCbx.getSelectedItem());
                pmn.setDob              (tanggalTxt.getText());
                pmn.setAlamat           (AlamatTxt.getText());
                pmn.setGender           ((String)jenisKelaminCbx.getSelectedItem());
                pmn.setAgama            ((String)agamaCbx.getSelectedItem());          
                crud.executeUpdatePemohon(pmn);
                JOptionPane.showMessageDialog(this, "Identitas Pemohon Berhasil di Perbaharui");
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                Vector<Pemohon> vPmn = crud.executeSelect();
                int i = 0;
                tableModelPemohon.setListPemohon(vPmn);
                tableModelPemohon.fireTableDataChanged();
                for (Pemohon pemohon : vPmn) {
                    tableModelPemohon.setValueAt(pemohon.getNo(), i, 1);
                    tableModelPemohon.setValueAt(pemohon.getId(), i, 2);
                    tableModelPemohon.setValueAt(pemohon.getNama_pemohon(), i, 3);
                    tableModelPemohon.setValueAt(pemohon.getPekerjaan(), i, 4);
                    tableModelPemohon.setValueAt(pemohon.getKewarganegaraan(), i, 5);
                    tableModelPemohon.setValueAt(pemohon.getDob(), i, 6);
                    tableModelPemohon.setValueAt(pemohon.getAlamat(), i, 7);
                    tableModelPemohon.setValueAt(pemohon.getGender(), i, 8);
                    tableModelPemohon.setValueAt(pemohon.getAgama(), i, 9);
                    i++;
                }
                System.out.println("Berhasil kawan namun belum ada yang berubah");
                initIdPemohon();
                resetKonten();
            } catch (SQLException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }               
        initButtonToFalse();
    }//GEN-LAST:event_perbaharuiBtnActionPerformed
    //hapus identitas pembuat surat pengantar
    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        int Pilih = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Akan Menghapus Tabel?","Warning",JOptionPane.YES_NO_OPTION);
        CRUD crud = new CRUD();
        Pemohon pmn = new Pemohon(idText.getText());
        if(Pilih == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(this, "Dibatalkan");
        } else if(Pilih == JOptionPane.YES_OPTION){
        try {
            crud.executeDeletePemohon(pmn);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Vector<Pemohon> vPmn = crud.executeSelect();
            int i = 0;
            tableModelPemohon.setListPemohon(vPmn);
            tableModelPemohon.fireTableDataChanged();
                for (Pemohon pemohon : vPmn) {
                    tableModelPemohon.setValueAt(pemohon.getNo(), i, 1);
                    tableModelPemohon.setValueAt(pemohon.getId(), i, 2);
                    tableModelPemohon.setValueAt(pemohon.getNama_pemohon(), i, 3);
                    tableModelPemohon.setValueAt(pemohon.getPekerjaan(), i, 4);
                    tableModelPemohon.setValueAt(pemohon.getKewarganegaraan(), i, 5);
                    tableModelPemohon.setValueAt(pemohon.getDob(), i, 6);
                    tableModelPemohon.setValueAt(pemohon.getAlamat(), i, 7);
                    tableModelPemohon.setValueAt(pemohon.getGender(), i, 8);
                    tableModelPemohon.setValueAt(pemohon.getAgama(), i, 9);
                    i++;
                }
                System.out.println("Berhasil kawan namun belum ada yang berubah");
                initIdPemohon();
                resetKonten();
            } catch (SQLException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            initButtonToFalse();
        }
        
    }//GEN-LAST:event_hapusBtnActionPerformed
    //cari user berdasarkan nama
    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        CRUD crud = new CRUD();
        try {
                Vector<Pemohon> vPmn = crud.searchingDataPemohon(cariTxt.getText());
                int i = 0;
                tableModelPemohon.setListPemohon(vPmn);
                tableModelPemohon.fireTableDataChanged();
                for (Pemohon pemohon : vPmn) {
                    tableModelPemohon.setValueAt(pemohon.getNo(), i, 1);
                    tableModelPemohon.setValueAt(pemohon.getId(), i, 2);
                    tableModelPemohon.setValueAt(pemohon.getNama_pemohon(), i, 3);
                    tableModelPemohon.setValueAt(pemohon.getPekerjaan(), i, 4);
                    tableModelPemohon.setValueAt(pemohon.getKewarganegaraan(), i, 5);
                    tableModelPemohon.setValueAt(pemohon.getDob(), i, 6);
                    tableModelPemohon.setValueAt(pemohon.getAlamat(), i, 7);
                    tableModelPemohon.setValueAt(pemohon.getGender(), i, 8);
                    tableModelPemohon.setValueAt(pemohon.getAgama(), i, 9);
                    i++;
                }
                System.out.println("Berhasil kawan namun belum ada yang berubah");
                initIdPemohon();
                resetKonten();
            } catch (SQLException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_cariBtnActionPerformed
    //kosongkan tabel pemohon
    private void resetLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetLabelMouseClicked
        if (evt.getClickCount() == 1) { 
        }
        if (evt.getClickCount() == 2) {
            int Pilih = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Akan Menghapus Tabel?","Warning",JOptionPane.YES_NO_OPTION);
            CRUD crud = new CRUD();
            if(Pilih == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(this, "Dibatalkan");
            }
            else if(Pilih == JOptionPane.YES_OPTION){
                try {
                    crud.executeResetTable();
                } catch (SQLException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    Vector<Pemohon> vPmn = crud.executeSelect();
                    int i = 0;
                    tableModelPemohon.setListPemohon(vPmn);
                    tableModelPemohon.fireTableDataChanged();
                        for (Pemohon pemohon : vPmn) {
                            tableModelPemohon.setValueAt(pemohon.getNo(), i, 1);
                            tableModelPemohon.setValueAt(pemohon.getId(), i, 2);
                            tableModelPemohon.setValueAt(pemohon.getNama_pemohon(), i, 3);
                            tableModelPemohon.setValueAt(pemohon.getPekerjaan(), i, 4);
                            tableModelPemohon.setValueAt(pemohon.getKewarganegaraan(), i, 5);
                            tableModelPemohon.setValueAt(pemohon.getDob(), i, 6);
                            tableModelPemohon.setValueAt(pemohon.getAlamat(), i, 7);
                            tableModelPemohon.setValueAt(pemohon.getGender(), i, 8);
                            tableModelPemohon.setValueAt(pemohon.getAgama(), i, 9);
                            i++;
                        }
                        System.out.println("Berhasil kawan namun belum ada yang berubah");
                        initIdPemohon();
                        resetKonten();
                    } catch (SQLException ex) {
                        Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }
    }//GEN-LAST:event_resetLabelMouseClicked
    //exit from application
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed
    //refresh identitas rt
    private void refreshIdentitasRtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshIdentitasRtMouseClicked
        try {
            if (evt.getClickCount() == 2) {
                identitasRt();
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshIdentitasRtMouseClicked
    //setting infomasi rt = menu setting->template
    private void perbaharuiInformasiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perbaharuiInformasiBtnActionPerformed
        SettingUI stui;
        try {
            stui = new SettingUI(this, true);
            stui.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_perbaharuiInformasiBtnActionPerformed
    //cekPersyaratan
    private void persyaratanLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persyaratanLabelMouseClicked
        if (evt.getClickCount() == 2) {
            prstn = new Persyaratan(this,true);
            prstn.setVisible(true);
        }
    }//GEN-LAST:event_persyaratanLabelMouseClicked
    //ketika label di click memunculkan preview dari surat yang siap dibuat
    private void labelPreviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPreviewMouseClicked
        Preview preview = new Preview();
        Transaksi transaksi = new Transaksi();
        int no = 1;
        int i = 0;
        if (namaTxt.getText().isEmpty() || pekerjaanTxt.getText().isEmpty() ||
            tanggalTxt.getText().isEmpty() || AlamatTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inputan tidak boleh kosong");
        }else{
            try {
                preview.setNo               (no);
                preview.setId               (idText.getText());
                preview.setNama_pemohon     (namaTxt.getText());
                preview.setPekerjaan        (pekerjaanTxt.getText());
                preview.setKewarganegaraan  ((String)kewarganegaraanCbx.getSelectedItem());
                preview.setDob              (tanggalTxt.getText());
                preview.setAlamat           (AlamatTxt.getText());
                preview.setGender           ((String)jenisKelaminCbx.getSelectedItem());
                preview.setAgama            ((String)agamaCbx.getSelectedItem());
                preview.setNo_rt            (labelNoRt.getText());
                preview.setNo_rw            (labelNoRw.getText());
                preview.setNama_rt          (labelNamaRt.getText());
                preview.setNama_rw          (labelNamaRw.getText());  
                preview.setDesa             (labelNamaDesa.getText());
                preview.setKecamatan        (labelNamaKecamatan.getText());
                preview.setKabupaten        (labelNamaKabupaten.getText());
                preview.setProvinsi         (labelNamaProvinsi.getText());
                
                transaksi.executeTruncate();
                transaksi.executeInsertTransaksi(preview);
                JOptionPane.showMessageDialog(this, "Lihat Preview");
                try{
                    JasperPrint jp = JasperFillManager.fillReport(
                            "src/com/psbo/eta/report/template_SuratPengantarKartuKeluarga.jasper"
                            , null
                            , MyConnection.getConnection()
                    );
                    JasperViewer.viewReport(jp, false);
                } catch (JRException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }               
    }//GEN-LAST:event_labelPreviewMouseClicked
    //print data ke pdf ketika yakin untuk di buat
    private void labelPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPrintMouseClicked
        
    }//GEN-LAST:event_labelPrintMouseClicked
    //kosongkan konten
    public void resetKonten(){
        initIdPemohon();
        namaTxt.setText("");
        tanggalTxt.setText("");
        AlamatTxt.setText("");
        pekerjaanTxt.setText("");
        kewarganegaraanCbx.setSelectedIndex(0);
        jenisKelaminCbx.setSelectedIndex(0);
        agamaCbx.setSelectedIndex(0);
    }
    //custome component for tablepemohon
    private void initComponentsCustomePemohon() {
        tablePemohon.setAutoCreateColumnsFromModel(false);
        tablePemohon.setModel(tableModelPemohon);
        tablePemohon.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrollPemohon.setViewportView(tablePemohon);
    }
    //loadtabelpemohon for tabelmodelpemohon
    private void loadTabelPemohon() {
        for (int i = 0; i < ColumnPemohon.COLUMN_SETTING.length; i++) {
            TableCellRenderer renderer;
            DefaultTableCellRenderer textRenderer = new DefaultTableCellRenderer();
            textRenderer.setHorizontalAlignment(ColumnPemohon.COLUMN_SETTING[i].getAligment());
            textRenderer.setFont(new Font("SansSerif", Font.PLAIN, 8));
            renderer = textRenderer;
            TableCellEditor editor = new DefaultCellEditor(new JTextField());
            TableColumn column = new TableColumn(i, ColumnPemohon.COLUMN_SETTING[i].getWidth(), renderer, editor);
            tablePemohon.addColumn(column);
        }
    }
    //initialisasi id pemohon
    private void initIdPemohon(){
        CRUD crud = new CRUD();
        Vector<Pemohon> vPmn;
        int i = 0;
        int no = 0;
        try {
            vPmn = crud.executeSelect();
            for (Pemohon pmn : vPmn) {
                no  = pmn.getNo();
                i++;
            }
            idText.setText("pm-0"+(no+1));
        } catch (SQLException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    com.jtattoo.plaf.mcwin.McWinLookAndFeel.setTheme("Large-Font", "Java Swing", "");
                    UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
                    
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Home().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatTxt;
    private javax.swing.JMenuItem aboutUsMenu;
    private javax.swing.JComboBox<String> agamaCbx;
    private javax.swing.JButton batalBtn;
    private javax.swing.JButton cariBtn;
    private javax.swing.JTextField cariTxt;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> jenisKelaminCbx;
    private javax.swing.JComboBox<String> kewarganegaraanCbx;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNamaDesa;
    private javax.swing.JLabel labelNamaKabupaten;
    private javax.swing.JLabel labelNamaKecamatan;
    private javax.swing.JLabel labelNamaProvinsi;
    private javax.swing.JLabel labelNamaRt;
    private javax.swing.JLabel labelNamaRw;
    private javax.swing.JLabel labelNoRt;
    private javax.swing.JLabel labelNoRw;
    private javax.swing.JLabel labelPreview;
    private javax.swing.JLabel labelPrint;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JPanel panelContain;
    private javax.swing.JPanel panelIdentitas;
    private javax.swing.JTextField pekerjaanTxt;
    private javax.swing.JButton perbaharuiBtn;
    private javax.swing.JButton perbaharuiInformasiBtn;
    private javax.swing.JLabel persyaratanLabel;
    private javax.swing.JMenuItem petunjukMenu;
    private javax.swing.JLabel refreshIdentitasRt;
    private javax.swing.JLabel refreshLabel;
    private javax.swing.JLabel resetLabel;
    private javax.swing.JScrollPane scrollPemohon;
    private javax.swing.JMenu settingMenu;
    private javax.swing.JMenuItem settingTemplate;
    private javax.swing.JMenuItem signout;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JTable tablePemohon;
    private javax.swing.JTextField tanggalTxt;
    // End of variables declaration//GEN-END:variables
}
