/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.psbo.eta.ui;

import com.psbo.eta.model.CekPersyaratan;
import com.psbo.eta.model.ModelPersyaratan;
import com.psbo.eta.model.Pemohon;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Multiverse
 * Develop by E.T.A
 */
public class Persyaratan extends javax.swing.JDialog {

    /**
     * Creates new form ModelPersyaratan
     */
    public Persyaratan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        checkPersyaratanPanel.setBorder(BorderFactory.createTitledBorder("Identitas Tempat Pembuat Pengantar Kartu Keluarga"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        checkPersyaratanPanel = new javax.swing.JPanel();
        aktaNikahCheck = new javax.swing.JCheckBox();
        aktaLahirCheck = new javax.swing.JCheckBox();
        KTPCheck = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        statusPersyaratanLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelNamaPemohon = new javax.swing.JLabel();
        schoolCmb = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Check Persyaratan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        checkPersyaratanPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aktaNikahCheck.setText("Akta Nikah");
        checkPersyaratanPanel.add(aktaNikahCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 117, -1, -1));

        aktaLahirCheck.setText("Akta Lahir");
        checkPersyaratanPanel.add(aktaLahirCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        KTPCheck.setText("KTP");
        checkPersyaratanPanel.add(KTPCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        jLabel2.setText("Pendidikan Terakhir");
        checkPersyaratanPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel3.setText("Kartu Identitas Pemohon");
        checkPersyaratanPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setText("Status Persyaratan ");
        checkPersyaratanPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel5.setText(":");
        checkPersyaratanPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel6.setText(":");
        checkPersyaratanPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel7.setText(":");
        checkPersyaratanPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        checkPersyaratanPanel.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 80, -1));

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        checkPersyaratanPanel.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 80, -1));

        statusPersyaratanLabel.setText("Belum Lengkap");
        checkPersyaratanPanel.add(statusPersyaratanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, 20));

        jLabel10.setText("Nama Pemohon");
        checkPersyaratanPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel11.setText(":");
        checkPersyaratanPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        labelNamaPemohon.setText("Okky Surya Lesmana");
        checkPersyaratanPanel.add(labelNamaPemohon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 140, 20));

        schoolCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "S1", "S2", "S3" }));
        checkPersyaratanPanel.add(schoolCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 110, -1));

        jPanel1.add(checkPersyaratanPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 670, 290));

        jLabel8.setText("Diisi sesuai dengan dokumen dari customer. apabila belum lengkap silahkan disimpan ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel9.setText("namun system tidak akan mengijinkan  Untuk Pembuatan Surat Pengantar Pembuatan Kartu Keluarga");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        CekPersyaratan cp = new CekPersyaratan();
        ModelPersyaratan mp = new ModelPersyaratan();
        if (!aktaNikahCheck.isSelected() || !aktaLahirCheck.isSelected() || !KTPCheck.isSelected()) {
            JOptionPane.showMessageDialog(this, "Silahkan Lengkapi Persyaratan");
        }else if (aktaNikahCheck.isSelected() && aktaLahirCheck.isSelected() && KTPCheck.isSelected()) {
            try {
                Vector<ModelPersyaratan> vModelPersyaratan;
                int i = 0;
                int no = 0;
                
                try {
                    vModelPersyaratan = cp.executeSelect();
                    for (ModelPersyaratan mope : vModelPersyaratan) {
                        no  = mope.getNo();
                        i++;
                    }
                    no = no+1;
                } catch (SQLException ex) {
                    Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                String id = "pr-0"+no;
                String aktaN = "1";
                String aktaL = "1";
                String ktp   = "1";
                String pendidikanTerakhir = "1";
                mp.setNo(no);
                mp.setId_persyaratan(id);
                mp.setAkta_nikah(aktaN);
                mp.setAkta_lahir(aktaL);
                mp.setKtp(ktp);
                mp.setPendidikan_terakhir(pendidikanTerakhir);
                mp.setStatus_persyaratan("sudah lengkap");
                JOptionPane.showMessageDialog(this, "Sudah tersimpan");
                cp.executeCheck(mp);
                JOptionPane.showMessageDialog(this, "Sudah tersimpan");
            } catch (SQLException ex) {
                Logger.getLogger(Persyaratan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    com.jtattoo.plaf.mcwin.McWinLookAndFeel.setTheme("Large-Font", "Java Swing", "");
                    UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Persyaratan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Persyaratan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Persyaratan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Persyaratan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Persyaratan dialog = new Persyaratan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox KTPCheck;
    private javax.swing.JCheckBox aktaLahirCheck;
    private javax.swing.JCheckBox aktaNikahCheck;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel checkPersyaratanPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNamaPemohon;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> schoolCmb;
    private javax.swing.JLabel statusPersyaratanLabel;
    // End of variables declaration//GEN-END:variables
}
