/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.psbo.eta.ui;

import com.psbo.eta.model.MyConnection;
import com.psbo.eta.model.Setting;
import com.psbo.eta.model.SettingToDatabaseTemplate;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Multiverse
 * Develop by E.T.A
 */
public class SettingUI extends javax.swing.JDialog {

    /**
     * Creates new form Setting
     */
    public SettingUI(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        isiFormulir();
    }
    
    public void isiFormulir() throws SQLException{
        
        SettingToDatabaseTemplate stdt = new SettingToDatabaseTemplate();
        Vector<Setting> vSetting = stdt.executeSelectSettingTemplate();
        
        for (Setting setting : vSetting) {
            no_rt.setText           (setting.getNo_rt());
            no_rw.setText           (setting.getNo_rw());
            namaRt.setText          (setting.getNama_rt());
            namaRw.setText          (setting.getNama_rw());
            namaDesa.setText        (setting.getDesa());
            namaKecamatan.setText   (setting.getKecamatan());
            namaKabupaten.setText   (setting.getKabupaten());
            namaProvinsi.setText    (setting.getProvinsi());
            
        }
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        namaRt = new javax.swing.JTextField();
        namaRw = new javax.swing.JTextField();
        namaDesa = new javax.swing.JTextField();
        namaKecamatan = new javax.swing.JTextField();
        namaKabupaten = new javax.swing.JTextField();
        namaProvinsi = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        no_rt = new javax.swing.JTextField();
        no_rw = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        settingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nama RT");
        settingPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel4.setText("Nama RW");
        settingPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel5.setText("Nama Desa/Kelurahan");
        settingPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel6.setText("Nama Kecamatan");
        settingPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel7.setText("Nama Kabupaten/Kota");
        settingPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel8.setText("Nama Provinsi");
        settingPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel9.setText(":");
        settingPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel10.setText(":");
        settingPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel11.setText(":");
        settingPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel12.setText(":");
        settingPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel13.setText(":");
        settingPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel14.setText(":");
        settingPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));
        settingPanel.add(namaRt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 180, -1));
        settingPanel.add(namaRw, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 180, -1));
        settingPanel.add(namaDesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 180, -1));
        settingPanel.add(namaKecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 180, -1));
        settingPanel.add(namaKabupaten, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 180, -1));
        settingPanel.add(namaProvinsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 180, -1));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        settingPanel.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 90, 30));

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        settingPanel.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 90, 30));

        no_rt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_rtActionPerformed(evt);
            }
        });
        settingPanel.add(no_rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 40, -1));
        settingPanel.add(no_rw, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, -1));

        jLabel3.setText("RT/RW");
        settingPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel15.setText(":");
        settingPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel16.setText("/");
        settingPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Setting");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(settingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(settingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        SettingToDatabaseTemplate stdb = new SettingToDatabaseTemplate();
        
        Vector<Setting> vSetting;
        if (namaRt.getText().isEmpty() || namaRw.getText().isEmpty() || namaDesa.getText().isEmpty() ||
            namaKecamatan.getText().isEmpty() || namaKabupaten.getText().isEmpty() || namaProvinsi.getText().isEmpty()
            ) {
            JOptionPane.showMessageDialog(this, "Formulir tidak boleh kosong");
        }
        else{
            String id = null;
            try {
                vSetting = stdb.executeSelectSettingTemplate();
                for (Setting setting : vSetting) {
                    id = setting.getId_setting();
                }
                String nort         = no_rt.getText();
                String norw         = no_rw.getText();
                String rt           = namaRt.getText();
                String rw           = namaRw.getText();
                String desa         = namaDesa.getText();
                String kecamatan    = namaKecamatan.getText();
                String kabupaten    = namaKabupaten.getText();
                String provinsi     = namaProvinsi.getText();

                Setting st = new Setting(
                        id, nort, norw, rt, rw, desa, kecamatan, kabupaten, provinsi
                );
                stdb.executeSaveSettingTemplate(st);
                
                JOptionPane.showMessageDialog(this, "data berhasil diperbaharui");
            } catch (SQLException ex) {
                Logger.getLogger(SettingUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
         no_rt.setText              ("");
            no_rw.setText           ("");
            namaRt.setText          ("");
            namaRw.setText          ("");
            namaDesa.setText        ("");
            namaKecamatan.setText   ("");
            namaKabupaten.setText   ("");
            namaProvinsi.setText    ("");
    }//GEN-LAST:event_resetBtnActionPerformed

    private void no_rtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_rtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_rtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    com.jtattoo.plaf.mcwin.McWinLookAndFeel.setTheme("Large-Font", "Java Swing", "");
                    UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SettingUI dialog = null;
                try {
                    dialog = new SettingUI(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(SettingUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField namaDesa;
    private javax.swing.JTextField namaKabupaten;
    private javax.swing.JTextField namaKecamatan;
    private javax.swing.JTextField namaProvinsi;
    private javax.swing.JTextField namaRt;
    private javax.swing.JTextField namaRw;
    private javax.swing.JTextField no_rt;
    private javax.swing.JTextField no_rw;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel settingPanel;
    // End of variables declaration//GEN-END:variables
}
